FileVersion = 1

[Project]
Name = "FuBattery"
TargetType = "BeefGUIApplication"
StartupObject = "FuKeys.Program"
DefaultNamespace = "FuKeys"

[Platform.Windows]
IconFile = "icons/bolt.ico"
Company = "Fusion LLC"
Product = "BatteryDisplay"

[Configs.Debug.Win64]
TargetDirectory = "$(WorkspaceDir)/dist"
TargetName = "$(ProjectName)_d"
LibPaths = ["Setupapi.lib", "Hid.lib", "Shell32.lib"]

[Configs.Release.Win64]
TargetDirectory = "$(WorkspaceDir)/dist"
LibPaths = ["Setupapi.lib", "Hid.lib", "Shell32.lib"]
